name: azeoo_flutter_sdk
description: A minimal modular Flutter SDK skeleton for Azeoo
publish_to: none
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  flutter_riverpod: ^2.0.0
  shared_preferences: ^2.0.0
  go_router: ^7.0.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
